//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTCT.ConstantContact {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AttributeCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringanyType")]
    [System.SerializableAttribute()]
    public class AttributeCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, object>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FormattedValueCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringstring")]
    [System.SerializableAttribute()]
    public class FormattedValueCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, string>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RelatedEntityCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfRelationshipEntityCollectionX_PsK4FkN")]
    [System.SerializableAttribute()]
    public class RelatedEntityCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<Microsoft.Xrm.Sdk.Relationship, Microsoft.Xrm.Sdk.EntityCollection>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LocalizedLabelCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="LocalizedLabel")]
    [System.SerializableAttribute()]
    public class LocalizedLabelCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.LocalizedLabel> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EntityReferenceCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="EntityReference")]
    [System.SerializableAttribute()]
    public class EntityReferenceCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.EntityReference> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AttributePrivilegeCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="AttributePrivilege")]
    [System.SerializableAttribute()]
    public class AttributePrivilegeCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.AttributePrivilege> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RelationshipQueryCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfRelationshipQueryBaseX_PsK4FkN")]
    [System.SerializableAttribute()]
    public class RelationshipQueryCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<Microsoft.Xrm.Sdk.Relationship, Microsoft.Xrm.Sdk.Query.QueryBase>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EntityMetadataCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="EntityMetadata")]
    [System.SerializableAttribute()]
    public class EntityMetadataCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.Metadata.EntityMetadata> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ParameterCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringanyType")]
    [System.SerializableAttribute()]
    public class ParameterCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, object>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ErrorDetailCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringanyType")]
    [System.SerializableAttribute()]
    public class ErrorDetailCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, object>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="QuickFindResultCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="QuickFindResult")]
    [System.SerializableAttribute()]
    public class QuickFindResultCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.QuickFindResult> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AttributeMappingCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="AttributeMapping")]
    [System.SerializableAttribute()]
    public class AttributeMappingCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.AttributeMapping> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppContext", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class AppContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SitemapIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CTCT.ConstantContact.AppEntityInfo[] appEntityInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CTCT.ConstantContact.AppInfo appInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] bpfIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] dashboardIdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SitemapId {
            get {
                return this.SitemapIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SitemapIdField, value) != true)) {
                    this.SitemapIdField = value;
                    this.RaisePropertyChanged("SitemapId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CTCT.ConstantContact.AppEntityInfo[] appEntityInfo {
            get {
                return this.appEntityInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.appEntityInfoField, value) != true)) {
                    this.appEntityInfoField = value;
                    this.RaisePropertyChanged("appEntityInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CTCT.ConstantContact.AppInfo appInfo {
            get {
                return this.appInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.appInfoField, value) != true)) {
                    this.appInfoField = value;
                    this.RaisePropertyChanged("appInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] bpfIds {
            get {
                return this.bpfIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.bpfIdsField, value) != true)) {
                    this.bpfIdsField = value;
                    this.RaisePropertyChanged("bpfIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] dashboardIds {
            get {
                return this.dashboardIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.dashboardIdsField, value) != true)) {
                    this.dashboardIdsField = value;
                    this.RaisePropertyChanged("dashboardIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppInfo", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Crm.Sdk.Messages")]
    [System.SerializableAttribute()]
    public partial class AppInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastModifiedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CTCT.ConstantContact.WebResourceInfo webResourceInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AppIdField, value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppUrl {
            get {
                return this.AppUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.AppUrlField, value) != true)) {
                    this.AppUrlField = value;
                    this.RaisePropertyChanged("AppUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastModifiedOn {
            get {
                return this.LastModifiedOnField;
            }
            set {
                if ((object.ReferenceEquals(this.LastModifiedOnField, value) != true)) {
                    this.LastModifiedOnField = value;
                    this.RaisePropertyChanged("LastModifiedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueName {
            get {
                return this.UniqueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueNameField, value) != true)) {
                    this.UniqueNameField = value;
                    this.RaisePropertyChanged("UniqueName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CTCT.ConstantContact.WebResourceInfo webResourceInfo {
            get {
                return this.webResourceInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.webResourceInfoField, value) != true)) {
                    this.webResourceInfoField = value;
                    this.RaisePropertyChanged("webResourceInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppEntityInfo", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Crm.Sdk.Messages")]
    [System.SerializableAttribute()]
    public partial class AppEntityInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ChartIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CTCT.ConstantContact.ArtifactIdType[] FormsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CTCT.ConstantContact.ArtifactIdType[] ViewsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ChartIds {
            get {
                return this.ChartIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChartIdsField, value) != true)) {
                    this.ChartIdsField = value;
                    this.RaisePropertyChanged("ChartIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityId {
            get {
                return this.EntityIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityIdField, value) != true)) {
                    this.EntityIdField = value;
                    this.RaisePropertyChanged("EntityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CTCT.ConstantContact.ArtifactIdType[] Forms {
            get {
                return this.FormsField;
            }
            set {
                if ((object.ReferenceEquals(this.FormsField, value) != true)) {
                    this.FormsField = value;
                    this.RaisePropertyChanged("Forms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CTCT.ConstantContact.ArtifactIdType[] Views {
            get {
                return this.ViewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ViewsField, value) != true)) {
                    this.ViewsField = value;
                    this.RaisePropertyChanged("Views");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtifactIdType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Crm.Sdk.Messages")]
    [System.SerializableAttribute()]
    public partial class ArtifactIdType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResourceInfo", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Crm.Sdk.Messages")]
    [System.SerializableAttribute()]
    public partial class WebResourceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WebResourceTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WebResourceType {
            get {
                return this.WebResourceTypeField;
            }
            set {
                if ((this.WebResourceTypeField.Equals(value) != true)) {
                    this.WebResourceTypeField = value;
                    this.RaisePropertyChanged("WebResourceType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairOfstringUserSearchFacetCollectiony3jr7a4n", Namespace="http://schemas.datacontract.org/2004/07/System.Collections.Generic")]
    [System.SerializableAttribute()]
    public partial struct KeyValuePairOfstringUserSearchFacetCollectiony3jr7a4n : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string keyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                if ((object.ReferenceEquals(this.keyField, value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DeletedMetadataCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Metadata/Query", ItemName="KeyValuePairOfDeletedMetadataFiltersArrayOfguidPlUv_PKtF")]
    [System.SerializableAttribute()]
    public class DeletedMetadataCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<Microsoft.Xrm.Sdk.Metadata.Query.DeletedMetadataFilters, System.Guid[]>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EndpointCollection", Namespace="http://schemas.microsoft.com/xrm/2014/Contracts", ItemName="KeyValuePairOfEndpointTypestringyDL0RVHi")]
    [System.SerializableAttribute()]
    public class EndpointCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<Microsoft.Xrm.Sdk.Organization.EndpointType, string>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppModuleInfo", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Crm.Sdk.Messages")]
    [System.SerializableAttribute()]
    public partial class AppModuleInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppDisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppUniqueNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebResourceUriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppDisplayName {
            get {
                return this.AppDisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AppDisplayNameField, value) != true)) {
                    this.AppDisplayNameField = value;
                    this.RaisePropertyChanged("AppDisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AppIdField, value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppUniqueName {
            get {
                return this.AppUniqueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AppUniqueNameField, value) != true)) {
                    this.AppUniqueNameField = value;
                    this.RaisePropertyChanged("AppUniqueName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppUri {
            get {
                return this.AppUriField;
            }
            set {
                if ((object.ReferenceEquals(this.AppUriField, value) != true)) {
                    this.AppUriField = value;
                    this.RaisePropertyChanged("AppUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppVersion {
            get {
                return this.AppVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.AppVersionField, value) != true)) {
                    this.AppVersionField = value;
                    this.RaisePropertyChanged("AppVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedOnField, value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebResourceUri {
            get {
                return this.WebResourceUriField;
            }
            set {
                if ((object.ReferenceEquals(this.WebResourceUriField, value) != true)) {
                    this.WebResourceUriField = value;
                    this.RaisePropertyChanged("WebResourceUri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OrganizationRequestCollection", Namespace="http://schemas.microsoft.com/xrm/2012/Contracts", ItemName="OrganizationRequest")]
    [System.SerializableAttribute()]
    public class OrganizationRequestCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.OrganizationRequest> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OrganizationResponseCollection", Namespace="http://schemas.microsoft.com/xrm/2012/Contracts", ItemName="ExecuteMultipleResponseItem")]
    [System.SerializableAttribute()]
    public class OrganizationResponseCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.ExecuteMultipleResponseItem> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailEngagementAggregate", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Xrm.Sdk")]
    [System.SerializableAttribute()]
    public partial class EmailEngagementAggregate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalAttachmentOpensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalEmailOpensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalEmailRepliesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalEmailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFollowedEmailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalLinkClicksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAttachmentOpens {
            get {
                return this.TotalAttachmentOpensField;
            }
            set {
                if ((this.TotalAttachmentOpensField.Equals(value) != true)) {
                    this.TotalAttachmentOpensField = value;
                    this.RaisePropertyChanged("TotalAttachmentOpens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalEmailOpens {
            get {
                return this.TotalEmailOpensField;
            }
            set {
                if ((this.TotalEmailOpensField.Equals(value) != true)) {
                    this.TotalEmailOpensField = value;
                    this.RaisePropertyChanged("TotalEmailOpens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalEmailReplies {
            get {
                return this.TotalEmailRepliesField;
            }
            set {
                if ((this.TotalEmailRepliesField.Equals(value) != true)) {
                    this.TotalEmailRepliesField = value;
                    this.RaisePropertyChanged("TotalEmailReplies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalEmails {
            get {
                return this.TotalEmailsField;
            }
            set {
                if ((this.TotalEmailsField.Equals(value) != true)) {
                    this.TotalEmailsField = value;
                    this.RaisePropertyChanged("TotalEmails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFollowedEmails {
            get {
                return this.TotalFollowedEmailsField;
            }
            set {
                if ((this.TotalFollowedEmailsField.Equals(value) != true)) {
                    this.TotalFollowedEmailsField = value;
                    this.RaisePropertyChanged("TotalFollowedEmails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalLinkClicks {
            get {
                return this.TotalLinkClicksField;
            }
            set {
                if ((this.TotalLinkClicksField.Equals(value) != true)) {
                    this.TotalLinkClicksField = value;
                    this.RaisePropertyChanged("TotalLinkClicks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppModuleCollection", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class AppModuleCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CTCT.ConstantContact.AppModuleInfo[] AppModuleInfoCollectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CTCT.ConstantContact.AppModuleInfo[] AppModuleInfoCollection {
            get {
                return this.AppModuleInfoCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.AppModuleInfoCollectionField, value) != true)) {
                    this.AppModuleInfoCollectionField = value;
                    this.RaisePropertyChanged("AppModuleInfoCollection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppModuleValidationResponse", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class AppModuleValidationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanBeActivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CTCT.ConstantContact.ValidationIssue[] ValidationIssueListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanBeActivated {
            get {
                return this.CanBeActivatedField;
            }
            set {
                if ((this.CanBeActivatedField.Equals(value) != true)) {
                    this.CanBeActivatedField = value;
                    this.RaisePropertyChanged("CanBeActivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CTCT.ConstantContact.ValidationIssue[] ValidationIssueList {
            get {
                return this.ValidationIssueListField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationIssueListField, value) != true)) {
                    this.ValidationIssueListField = value;
                    this.RaisePropertyChanged("ValidationIssueList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationIssue", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class ValidationIssue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CRMErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ComponentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ComponentSubTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ComponentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CTCT.ConstantContact.ErrorType ErrorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ParentEntityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentEntityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CTCT.ConstantContact.Component[] RequiredComponentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CRMErrorCode {
            get {
                return this.CRMErrorCodeField;
            }
            set {
                if ((this.CRMErrorCodeField.Equals(value) != true)) {
                    this.CRMErrorCodeField = value;
                    this.RaisePropertyChanged("CRMErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ComponentId {
            get {
                return this.ComponentIdField;
            }
            set {
                if ((this.ComponentIdField.Equals(value) != true)) {
                    this.ComponentIdField = value;
                    this.RaisePropertyChanged("ComponentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComponentSubType {
            get {
                return this.ComponentSubTypeField;
            }
            set {
                if ((this.ComponentSubTypeField.Equals(value) != true)) {
                    this.ComponentSubTypeField = value;
                    this.RaisePropertyChanged("ComponentSubType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComponentType {
            get {
                return this.ComponentTypeField;
            }
            set {
                if ((this.ComponentTypeField.Equals(value) != true)) {
                    this.ComponentTypeField = value;
                    this.RaisePropertyChanged("ComponentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CTCT.ConstantContact.ErrorType ErrorType {
            get {
                return this.ErrorTypeField;
            }
            set {
                if ((this.ErrorTypeField.Equals(value) != true)) {
                    this.ErrorTypeField = value;
                    this.RaisePropertyChanged("ErrorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ParentEntityId {
            get {
                return this.ParentEntityIdField;
            }
            set {
                if ((this.ParentEntityIdField.Equals(value) != true)) {
                    this.ParentEntityIdField = value;
                    this.RaisePropertyChanged("ParentEntityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentEntityName {
            get {
                return this.ParentEntityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentEntityNameField, value) != true)) {
                    this.ParentEntityNameField = value;
                    this.RaisePropertyChanged("ParentEntityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CTCT.ConstantContact.Component[] RequiredComponents {
            get {
                return this.RequiredComponentsField;
            }
            set {
                if ((object.ReferenceEquals(this.RequiredComponentsField, value) != true)) {
                    this.RequiredComponentsField = value;
                    this.RaisePropertyChanged("RequiredComponents");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorType", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    public enum ErrorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Component", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class Component : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ComponentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ComponentSubTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ComponentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ParentEntityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentEntityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchemaNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ComponentId {
            get {
                return this.ComponentIdField;
            }
            set {
                if ((this.ComponentIdField.Equals(value) != true)) {
                    this.ComponentIdField = value;
                    this.RaisePropertyChanged("ComponentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComponentSubType {
            get {
                return this.ComponentSubTypeField;
            }
            set {
                if ((this.ComponentSubTypeField.Equals(value) != true)) {
                    this.ComponentSubTypeField = value;
                    this.RaisePropertyChanged("ComponentSubType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComponentType {
            get {
                return this.ComponentTypeField;
            }
            set {
                if ((this.ComponentTypeField.Equals(value) != true)) {
                    this.ComponentTypeField = value;
                    this.RaisePropertyChanged("ComponentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ParentEntityId {
            get {
                return this.ParentEntityIdField;
            }
            set {
                if ((this.ParentEntityIdField.Equals(value) != true)) {
                    this.ParentEntityIdField = value;
                    this.RaisePropertyChanged("ParentEntityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentEntityName {
            get {
                return this.ParentEntityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentEntityNameField, value) != true)) {
                    this.ParentEntityNameField = value;
                    this.RaisePropertyChanged("ParentEntityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchemaName {
            get {
                return this.SchemaNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SchemaNameField, value) != true)) {
                    this.SchemaNameField = value;
                    this.RaisePropertyChanged("SchemaName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AuditPartitionDetailCollection", Namespace="http://schemas.microsoft.com/crm/2011/Contracts", ItemName="AuditPartitionDetail")]
    [System.SerializableAttribute()]
    public class AuditPartitionDetailCollection : System.Collections.Generic.List<Microsoft.Crm.Sdk.Messages.AuditPartitionDetail> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessProcessFlowContext", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class BusinessProcessFlowContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ActionStepIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid BusinessProcessFlowIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid BusinessProcessFlowInstanceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ActionStepId {
            get {
                return this.ActionStepIdField;
            }
            set {
                if ((this.ActionStepIdField.Equals(value) != true)) {
                    this.ActionStepIdField = value;
                    this.RaisePropertyChanged("ActionStepId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BusinessProcessFlowId {
            get {
                return this.BusinessProcessFlowIdField;
            }
            set {
                if ((this.BusinessProcessFlowIdField.Equals(value) != true)) {
                    this.BusinessProcessFlowIdField = value;
                    this.RaisePropertyChanged("BusinessProcessFlowId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BusinessProcessFlowInstanceId {
            get {
                return this.BusinessProcessFlowInstanceIdField;
            }
            set {
                if ((this.BusinessProcessFlowInstanceIdField.Equals(value) != true)) {
                    this.BusinessProcessFlowInstanceIdField = value;
                    this.RaisePropertyChanged("BusinessProcessFlowInstanceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CacheItem", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class CacheItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultType", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    public enum FaultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CrmException = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClrException = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Assertion = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Watson = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="QueryByEntityNameDictionary", Namespace="http://schemas.microsoft.com/crm/2011/Contracts", ItemName="KeyValuePairOfstringQueryBasegUGIFE1S")]
    [System.SerializableAttribute()]
    public class QueryByEntityNameDictionary : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, Microsoft.Xrm.Sdk.Query.QueryBase>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResetSyncStateInfo", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class ResetSyncStateInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] EntityIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ObjectTypeCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] EntityIds {
            get {
                return this.EntityIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityIdsField, value) != true)) {
                    this.EntityIdsField = value;
                    this.RaisePropertyChanged("EntityIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ObjectTypeCode {
            get {
                return this.ObjectTypeCodeField;
            }
            set {
                if ((this.ObjectTypeCodeField.Equals(value) != true)) {
                    this.ObjectTypeCodeField = value;
                    this.RaisePropertyChanged("ObjectTypeCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SdkMessageProcessingStepImageRegistration", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class SdkMessageProcessingStepImageRegistration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AttributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessagePropertyNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Attributes {
            get {
                return this.AttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributesField, value) != true)) {
                    this.AttributesField = value;
                    this.RaisePropertyChanged("Attributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityAlias {
            get {
                return this.EntityAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityAliasField, value) != true)) {
                    this.EntityAliasField = value;
                    this.RaisePropertyChanged("EntityAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImageType {
            get {
                return this.ImageTypeField;
            }
            set {
                if ((this.ImageTypeField.Equals(value) != true)) {
                    this.ImageTypeField = value;
                    this.RaisePropertyChanged("ImageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessagePropertyName {
            get {
                return this.MessagePropertyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagePropertyNameField, value) != true)) {
                    this.MessagePropertyNameField = value;
                    this.RaisePropertyChanged("MessagePropertyName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SdkMessageProcessingStepRegistration", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class SdkMessageProcessingStepRegistration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomConfigurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilteringAttributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CTCT.ConstantContact.SdkMessageProcessingStepImageRegistration[] ImagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ImpersonatingUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvocationSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PluginTypeFriendlyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PluginTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryEntityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondaryEntityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupportedDeploymentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomConfiguration {
            get {
                return this.CustomConfigurationField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomConfigurationField, value) != true)) {
                    this.CustomConfigurationField = value;
                    this.RaisePropertyChanged("CustomConfiguration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilteringAttributes {
            get {
                return this.FilteringAttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilteringAttributesField, value) != true)) {
                    this.FilteringAttributesField = value;
                    this.RaisePropertyChanged("FilteringAttributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CTCT.ConstantContact.SdkMessageProcessingStepImageRegistration[] Images {
            get {
                return this.ImagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagesField, value) != true)) {
                    this.ImagesField = value;
                    this.RaisePropertyChanged("Images");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ImpersonatingUserId {
            get {
                return this.ImpersonatingUserIdField;
            }
            set {
                if ((this.ImpersonatingUserIdField.Equals(value) != true)) {
                    this.ImpersonatingUserIdField = value;
                    this.RaisePropertyChanged("ImpersonatingUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvocationSource {
            get {
                return this.InvocationSourceField;
            }
            set {
                if ((this.InvocationSourceField.Equals(value) != true)) {
                    this.InvocationSourceField = value;
                    this.RaisePropertyChanged("InvocationSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageName {
            get {
                return this.MessageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageNameField, value) != true)) {
                    this.MessageNameField = value;
                    this.RaisePropertyChanged("MessageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((this.ModeField.Equals(value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PluginTypeFriendlyName {
            get {
                return this.PluginTypeFriendlyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PluginTypeFriendlyNameField, value) != true)) {
                    this.PluginTypeFriendlyNameField = value;
                    this.RaisePropertyChanged("PluginTypeFriendlyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PluginTypeName {
            get {
                return this.PluginTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PluginTypeNameField, value) != true)) {
                    this.PluginTypeNameField = value;
                    this.RaisePropertyChanged("PluginTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryEntityName {
            get {
                return this.PrimaryEntityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryEntityNameField, value) != true)) {
                    this.PrimaryEntityNameField = value;
                    this.RaisePropertyChanged("PrimaryEntityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondaryEntityName {
            get {
                return this.SecondaryEntityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryEntityNameField, value) != true)) {
                    this.SecondaryEntityNameField = value;
                    this.RaisePropertyChanged("SecondaryEntityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stage {
            get {
                return this.StageField;
            }
            set {
                if ((this.StageField.Equals(value) != true)) {
                    this.StageField = value;
                    this.RaisePropertyChanged("Stage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupportedDeployment {
            get {
                return this.SupportedDeploymentField;
            }
            set {
                if ((this.SupportedDeploymentField.Equals(value) != true)) {
                    this.SupportedDeploymentField = value;
                    this.RaisePropertyChanged("SupportedDeployment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyncAction", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    public enum SyncAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Services", ConfigurationName="ConstantContact.IOrganizationService")]
    public interface IOrganizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Cre" +
            "ate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Cre" +
            "ateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Cre" +
            "ateOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        System.Guid Create(Microsoft.Xrm.Sdk.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Cre" +
            "ate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Cre" +
            "ateResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateAsync(Microsoft.Xrm.Sdk.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieve", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        Microsoft.Xrm.Sdk.Entity Retrieve(string entityName, System.Guid id, Microsoft.Xrm.Sdk.Query.ColumnSet columnSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieve", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveResponse")]
        System.Threading.Tasks.Task<Microsoft.Xrm.Sdk.Entity> RetrieveAsync(string entityName, System.Guid id, Microsoft.Xrm.Sdk.Query.ColumnSet columnSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Upd" +
            "ate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Upd" +
            "ateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Upd" +
            "ateOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        void Update(Microsoft.Xrm.Sdk.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Upd" +
            "ate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Upd" +
            "ateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Microsoft.Xrm.Sdk.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Del" +
            "ete", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Del" +
            "eteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Del" +
            "eteOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        void Delete(string entityName, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Del" +
            "ete", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Del" +
            "eteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string entityName, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Exe" +
            "cute", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Exe" +
            "cuteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Exe" +
            "cuteOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        Microsoft.Xrm.Sdk.OrganizationResponse Execute(Microsoft.Xrm.Sdk.OrganizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Exe" +
            "cute", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Exe" +
            "cuteResponse")]
        System.Threading.Tasks.Task<Microsoft.Xrm.Sdk.OrganizationResponse> ExecuteAsync(Microsoft.Xrm.Sdk.OrganizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ass" +
            "ociate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ass" +
            "ociateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ass" +
            "ociateOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        void Associate(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, CTCT.ConstantContact.EntityReferenceCollection relatedEntities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ass" +
            "ociate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ass" +
            "ociateResponse")]
        System.Threading.Tasks.Task AssociateAsync(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, CTCT.ConstantContact.EntityReferenceCollection relatedEntities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Dis" +
            "associate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Dis" +
            "associateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Dis" +
            "associateOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        void Disassociate(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, CTCT.ConstantContact.EntityReferenceCollection relatedEntities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Dis" +
            "associate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Dis" +
            "associateResponse")]
        System.Threading.Tasks.Task DisassociateAsync(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, CTCT.ConstantContact.EntityReferenceCollection relatedEntities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveMultiple", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveMultipleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveMultipleOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Xrm.Sdk.Query.QueryExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Xrm.Sdk.Query.QueryByAttribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Xrm.Sdk.Query.FetchExpression))]
        Microsoft.Xrm.Sdk.EntityCollection RetrieveMultiple(Microsoft.Xrm.Sdk.Query.QueryBase query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveMultiple", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveMultipleResponse")]
        System.Threading.Tasks.Task<Microsoft.Xrm.Sdk.EntityCollection> RetrieveMultipleAsync(Microsoft.Xrm.Sdk.Query.QueryBase query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrganizationServiceChannel : CTCT.ConstantContact.IOrganizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrganizationServiceClient : System.ServiceModel.ClientBase<CTCT.ConstantContact.IOrganizationService>, CTCT.ConstantContact.IOrganizationService {
        
        public OrganizationServiceClient() {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid Create(Microsoft.Xrm.Sdk.Entity entity) {
            return base.Channel.Create(entity);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateAsync(Microsoft.Xrm.Sdk.Entity entity) {
            return base.Channel.CreateAsync(entity);
        }
        
        public Microsoft.Xrm.Sdk.Entity Retrieve(string entityName, System.Guid id, Microsoft.Xrm.Sdk.Query.ColumnSet columnSet) {
            return base.Channel.Retrieve(entityName, id, columnSet);
        }
        
        public System.Threading.Tasks.Task<Microsoft.Xrm.Sdk.Entity> RetrieveAsync(string entityName, System.Guid id, Microsoft.Xrm.Sdk.Query.ColumnSet columnSet) {
            return base.Channel.RetrieveAsync(entityName, id, columnSet);
        }
        
        public void Update(Microsoft.Xrm.Sdk.Entity entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Microsoft.Xrm.Sdk.Entity entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string entityName, System.Guid id) {
            base.Channel.Delete(entityName, id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string entityName, System.Guid id) {
            return base.Channel.DeleteAsync(entityName, id);
        }
        
        public Microsoft.Xrm.Sdk.OrganizationResponse Execute(Microsoft.Xrm.Sdk.OrganizationRequest request) {
            return base.Channel.Execute(request);
        }
        
        public System.Threading.Tasks.Task<Microsoft.Xrm.Sdk.OrganizationResponse> ExecuteAsync(Microsoft.Xrm.Sdk.OrganizationRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public void Associate(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, CTCT.ConstantContact.EntityReferenceCollection relatedEntities) {
            base.Channel.Associate(entityName, entityId, relationship, relatedEntities);
        }
        
        public System.Threading.Tasks.Task AssociateAsync(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, CTCT.ConstantContact.EntityReferenceCollection relatedEntities) {
            return base.Channel.AssociateAsync(entityName, entityId, relationship, relatedEntities);
        }
        
        public void Disassociate(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, CTCT.ConstantContact.EntityReferenceCollection relatedEntities) {
            base.Channel.Disassociate(entityName, entityId, relationship, relatedEntities);
        }
        
        public System.Threading.Tasks.Task DisassociateAsync(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, CTCT.ConstantContact.EntityReferenceCollection relatedEntities) {
            return base.Channel.DisassociateAsync(entityName, entityId, relationship, relatedEntities);
        }
        
        public Microsoft.Xrm.Sdk.EntityCollection RetrieveMultiple(Microsoft.Xrm.Sdk.Query.QueryBase query) {
            return base.Channel.RetrieveMultiple(query);
        }
        
        public System.Threading.Tasks.Task<Microsoft.Xrm.Sdk.EntityCollection> RetrieveMultipleAsync(Microsoft.Xrm.Sdk.Query.QueryBase query) {
            return base.Channel.RetrieveMultipleAsync(query);
        }
    }
}
